[package]
name = "chaos-execute"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.9.0"
glib = "0.9.0"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }

[profile.release]
opt-level = 3